# Generated by Django 4.0.4 on 2022-04-27 09:58

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(default='987654321', max_length=9, validators=[store.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='product',
            name='province',
            field=models.CharField(choices=[('Lower Silesia', 'Lower Silesia'), ('Kuyavia-Pomerania', 'Kuyavia-Pomerania'), ('Lodzkie', 'Lodzkie'), ('Lublin', 'Lublin'), ('Lubusz', 'Lubusz'), ('Lesser Poland', 'Lesser Poland'), ('Masovia', 'Masovia'), ('Subcarpathia', 'Subcarpathia'), ('Pomerania', 'Pomerania'), ('Silesia', 'Silesia'), ('Warmia-Masuria', 'Warmia-Masuria'), ('Greater Poland', 'Greater Poland'), ('West Pomerania', 'West Pomerania')], default='Poland', max_length=64),
        ),
    ]
